server:
  port: ${MEMBER_PORT:8081}

spring:
  application:
    name: member-service
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/smarketing_member}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

jwt:
  secret: ${JWT_SECRET:mySecretKeyForJWTTokenGenerationAndValidation123456789}
  access-token-validity: ${JWT_ACCESS_VALIDITY:3600000}
  refresh-token-validity: ${JWT_REFRESH_VALIDITY:604800000}

logging:
  level:
    com.won.smarketing: ${LOG_LEVEL:DEBUG}
