server:
  port: ${SERVER_PORT:8083}

spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  application:
    name: marketing-content-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:MarketingContentDB}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

jwt:
  secret: ${JWT_SECRET:mySecretKeyForJWTTokenGenerationAndValidation123456789}
  access-token-validity: ${JWT_ACCESS_VALIDITY:3600000}
  refresh-token-validity: ${JWT_REFRESH_VALIDITY:604800000}

logging:
  level:
    com.won.smarketing: ${LOG_LEVEL:DEBUG}
external:
  ai-service:
    base-url: ${AI_SERVICE_BASE_URL:http://20.249.113.247:5001}
azure:
  storage:
    account-name: ${AZURE_STORAGE_ACCOUNT_NAME:stdigitalgarage02}
    account-key: ${AZURE_STORAGE_ACCOUNT_KEY:}
    endpoint: ${AZURE_STORAGE_ENDPOINT:https://stdigitalgarage02.blob.core.windows.net}
    container:
      menu-images: ${AZURE_STORAGE_MENU_CONTAINER:smarketing-menu-images}
      store-images: ${AZURE_STORAGE_STORE_CONTAINER:smarketing-store-images}
    max-file-size: ${AZURE_STORAGE_MAX_FILE_SIZE:10485760} # 10MB
management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

info:
  app:
    name: ${APP_NAME:smarketing-content}
    version: "1.0.0-MVP"
    description: "AI 마케팅 서비스 MVP - content"