apiVersion: apps/v1
kind: Deployment
metadata:
  name: member
  namespace: smarketing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: member
  template:
    metadata:
      labels:
        app: member
    spec:
      containers:
      - name: member
        image: acrdigitalgarage02.azurecr.io/member:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        resources:
          requests:
            memory: "256Mi"
            cpu: "256m"
          limits:
            memory: "1024Mi" 
            cpu: "1024m"
